baseURL = "https://www.ayulog.xyz/"
languageCode = "zh-cn"              # å·²ä¿®æ”¹ä¸ºä¸­æ–‡
title = "aYu's web3 logs"           # ä¿®æ”¹ä¸ºä½ è‡ªå·±çš„åšå®¢æ ‡é¢˜
theme = "PaperMod"

# è¿™æ˜¯ PaperMod ä¸»é¢˜éœ€è¦çš„æ ¸å¿ƒå‚æ•°æ®µè½
[params]

# åœ¨ [params] çš„ä¸‹é¢æ·»åŠ è¿™æ®µ
[params.homeInfoParams]
Title = "Hello ğŸ‘‹"
Content = "æ¬¢è¿æ¥åˆ°é˜¿å®‡çš„æˆé•¿æ—¥å¿—ã€‚åœ¨è¿™é‡Œï¼Œæˆ‘ä¼šåˆ†äº«å…³äº Web3ã€ä»£å¸ç»æµå’Œä¸ªäººæˆé•¿çš„æ€è€ƒä¸è®°å½•ã€‚"

# ä¸ªäººèµ„æ–™æ¨¡å¼é…ç½®
[params.profileMode]
enabled = false
title = "aYu"                                                                              # æ˜¾ç¤ºåœ¨å¤´åƒä¸‹çš„åå­—
subtitle = "åè®®çº§ä»£å¸ç»æµæ¨¡å‹åˆ†æ | Web3 | ä¸ªäººæˆé•¿"                                                     # ä¸€å¥ç®€ä»‹
imageUrl = "https://pbs.twimg.com/profile_images/1966702157790670849/EHdO4yup_400x400.jpg" # åœ¨è¿™é‡Œæ›¿æ¢æˆä½ çš„å¤´åƒå›¾ç‰‡é“¾æ¥, ä¾‹å¦‚ GitHub å¤´åƒ
imageTitle = "æˆ‘çš„å¤´åƒ"
imageWidth = 120
imageHeight = 120

# ç¤¾äº¤å›¾æ ‡
[[params.socialIcons]]
name = "github"
url = "https://github.com/aYu-flows" # æ›¿æ¢æˆä½ çš„ GitHub ä¸»é¡µé“¾æ¥

[[params.socialIcons]]
name = "twitter"
url = "https://x.com/AyuFlows" # æ›¿æ¢æˆä½ çš„ GitHub ä¸»é¡µé“¾æ¥

[[params.socialIcons]]
name = "mirror"
url = "https://mirror.xyz/0x47d30F192071B38982Cee7bCE2C41De23F159Af9" # æ›¿æ¢æˆä½ çš„ GitHub ä¸»é¡µé“¾æ¥


# ç½‘ç«™ä¸»èœå•é…ç½®
[[menu.main]]
identifier = "categories"
name = "åˆ†ç±»"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20
