baseURL = "https://www.ayulog.xyz/"
languageCode = "zh-cn"              # 已修改为中文
title = "阿宇的成长日志"                   # 修改为你自己的博客标题
theme = "PaperMod"

# 这是 PaperMod 主题需要的核心参数段落
[params]
# 个人资料模式配置
[params.profileMode]
enabled = true
title = "阿宇 (aYu-flows)"                                                                   # 显示在头像下的名字
subtitle = "协议级代币经济模型分析 | Web3 | 个人成长"                                                     # 一句简介
imageUrl = "https://pbs.twimg.com/profile_images/1966702157790670849/EHdO4yup_400x400.jpg" # 在这里替换成你的头像图片链接, 例如 GitHub 头像
imageTitle = "我的头像"
imageWidth = 120
imageHeight = 120

# 社交图标
[[params.socialIcons]]
name = "github"
url = "https://github.com/aYu-flows" # 替换成你的 GitHub 主页链接

# 网站主菜单配置
[[menu.main]]
identifier = "archives"
name = "归档"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "search"
name = "搜索"
url = "/search/"
weight = 20
